### ISSUE TITLE
Error R10 (Boot timeout) -> Web process failed to bind to $PORT 

### ISSUE THREAD

**Issue by ericaroy** [ProjectBotTeam/projectBot#18]
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

**Comment by ericaroy** [comment]
seems to not startup on heroku

**Comment by ericaroy** [comment]
seems to be a port issue with heroku

**Comment by ghost** [comment]
Worked after pushing to Heroku.
